sales_hierarchy:
  - task_name: task_climate
    name: climate
    job_id: 10001
    extract: true
    source: oracle
    connection: ["oracle_credentials"]
    source_type: db  # possible values: db, files, api
    destination: bq
    description: ""

    # Table Info
    #    groupby_columns:
    #      tdate:
    #        column_type: timestamp
    #        column_format:
    #
    #      id:
    #        column_type: id

    groupby_column: 'tdate'
    groupby_format: 'YYYY-MM-DD HH24:MI:SS'

    incremental_column:
      tdate:
        column_type: timestamp
        column_format: 'YYYY-MM-DD HH24:MI:SS'
      meantemp:
        column_type: id

    schema_details:
      tdate: TIMESTAMP
      MEANTEMP: VARCHAR2
      wind_speed: VARCHAR2
      meanpressure: VARCHAR2
    drop_columns:
      - test
      - humidity     

    # Query/Frequency info
    query: "select * from climate "
    batch_size: 10000
    where_clause: ""
    use_adaptive_framework: true

    # destination_details
#    gcp_project_id: turing-nature-374608
#    gcp_bq_dataset_name: test_dataset2

    target_project_id: turing-nature-374608
    target_bq_dataset_name: test_dataset2
    target_table_name: test_climate_bq2
    target_operation: a # (a: for append, t: for truncate)
